# Generated by Django 4.0.3 on 2022-03-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Role'},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
