# Generated by Django 4.0.2 on 2022-02-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=50)),
                ('batchdescription', models.CharField(max_length=50)),
                ('batchStartDate', models.DateField()),
                ('batchEndDate', models.DateField()),
                ('courseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='BatchTime',
            fields=[
                ('batchTimeId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchDay', models.DateField()),
                ('BatchTime', models.TimeField()),
                ('BatchDuration', models.DurationField()),
                ('batchId', models.ManyToManyField(to='batch.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchDetails',
            fields=[
                ('batch_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('batchId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
            ],
        ),
    ]
